version: '3'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ms-sql-server
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "P@ssw0rd"
    ports:
      - "1433:1433"
  mini-project:
    build: .
    container_name: ayus-mini-project
    environment:
      DBServer: "ms-sql-server"
    ports:
      - "8080:5000"
