// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniProject.API.Data;

#nullable disable

namespace MiniProject.API.Data.Migrations
{
    [DbContext(typeof(MiniProjectContext))]
    [Migration("20231212111721_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniProject.API.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TMCustomer");
                });

            modelBuilder.Entity("MiniProject.API.Entities.CustomerPromo", b =>
                {
                    b.Property<int>("IdCustomer")
                        .HasColumnType("int");

                    b.Property<int>("IdPromo")
                        .HasColumnType("int");

                    b.HasKey("IdCustomer", "IdPromo");

                    b.HasIndex("IdPromo");

                    b.ToTable("TTPromo");
                });

            modelBuilder.Entity("MiniProject.API.Entities.Promo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Discount")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("PromoName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TMPromo");
                });

            modelBuilder.Entity("MiniProject.API.Entities.CustomerPromo", b =>
                {
                    b.HasOne("MiniProject.API.Entities.Customer", "Customer")
                        .WithMany("CustomerPromos")
                        .HasForeignKey("IdCustomer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniProject.API.Entities.Promo", "Promo")
                        .WithMany("CustomerPromos")
                        .HasForeignKey("IdPromo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Promo");
                });

            modelBuilder.Entity("MiniProject.API.Entities.Customer", b =>
                {
                    b.Navigation("CustomerPromos");
                });

            modelBuilder.Entity("MiniProject.API.Entities.Promo", b =>
                {
                    b.Navigation("CustomerPromos");
                });
#pragma warning restore 612, 618
        }
    }
}
